### ISSUE TITLE
Projectiles modules docs broken

### ISSUE THREAD

**Issue by technodono** [PGMDev/Website#40]
The projectiles module for the projectile feature is broken... It refers to https://pgm.dev/docs/reference/entities/entity-types
as all the entities a projectile can be but half of the names listed there don't work or have to be changed to work

e.g. Primed TNT -> TNTprimed

Ender pearl > Enderpearl
Wither Skull >  Witherskull
Creeper -> ?
[this one doesn't work]

On top that no entities fired can't have nbt attached to them... oversight?

**Comment by CoWinkKeyDinkInc** [comment]
PGM doesn't use the same entity names for projectiles. For reference try using the tested list that MonsieurApple links in this section. I assume that they were given different names within PGM for whatever reason instead of using the bukkit name. So for the first two you should be using `EnderPearl` and `WitherSkull`. Have you checked if you enabled mob spawning for the creeper projectile?

https://gist.github.com/tonybruess/4617111

While going through this list I seen that the boats actually fire this time and are controlled by the bow charge. I'll be going through the list to see if any of the non working entities work now.

**Comment by CoWinkKeyDinkInc** [comment]
`WitherSkull` is properly visible, though it moves very fast from bow charge, can probably be adjusted with the bow velocity tags.
`EnderCrystal` has the same behaviour.
`Painting` still doesn't work, throws a EventException and NullPointerException :(
`Firework` also works in the same behaviour, pretty fast though and bounces off the ground.

**Comment by CoWinkKeyDinkInc** [comment]
Updated in b1c0e579e7aaaafbad4b340472235262ebd6a6ab. Tell me what you think! :)
